data:
  path_to_annotation: "/data/coco/annotations/captions_train2017.json"
  path_to_images: "data/coco/images/train2017"
  sequence_length: 64
  image_size: 224
  tokenizer_name: gpt2
  bos_str: <|startoftext|>
  eos_str: <|endoftext|>

vision_encoder:
  embed_dim: 512
  backbone_name: resnet50
  pretrained: True

text_encoder:
  embed_dim: 512
  num_layers: 8
  num_heads: 8

clip_model:
  embed_dim: 512
  temperature: 0.07

train:
  batch_size: 2
  num_workers: 16
  num_epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.0001
  warmup_steps: 1000
  log_every_n_steps: 100
  save_every_n_steps: 1000
  random_seed: 92837465