data:
  path_to_train_annotation: "coco/annotations/captions_train2017.json"
  path_to_train_images: "coco/images/train2017"
  path_to_val_annotation: "coco/annotations/captions_val2017.json"
  path_to_val_images: "coco/images/val2017"
  sequence_length: 64
  image_size: 224
  tokenizer_name: gpt2
  bos_str: <|startoftext|>
  eos_str: <|endoftext|>

vision_encoder:
  embed_dim: 512
  backbone_name: resnet101
  pretrained: False

text_encoder:
  embed_dim: 512
  num_layers: 8
  num_heads: 8

clip_model:
  embed_dim: 512
  temperature: 0.07

train:
  batch_size: 50
  num_workers: 32
  num_epochs: 3
  learning_rate: 0.0003
  weight_decay: 0.0001
  warmup_steps: 1000
  validate_every_n_epochs: 1
  save_every_n_epochs: 1
  random_seed: 92837465
  device: cuda:0